Repository IUT-Blagnac/sae3-01-devapp-g1a-1, pull requests merged in 2022-12, with the labels that each got.

#39 Mise à jour Doc BD
  Documentation/Livrables/BD/DC.puml
  Documentation/Livrables/BD/DiagrameDeClasse.png
  Documentation/Livrables/BD/SchemaRelationel.adoc
  Documentation/Livrables/BD/SchémaRelationnel.png
  Documentation/Livrables/BD/dicoDesDonneed.ods
Labels: type: DOCS

#40 Ménage du readme
  README.adoc
Labels: type: DOCS

#42 Mise à jour du SEP
  Documentation/Livrables/Site Web/DiagramEnchainementPagesV2.png
  Documentation/Livrables/Site Web/SchémaEnchainementPages.png
Labels: type: DOCS

#43 changement de lien de la version
  README.adoc
Labels: type: DOCS

#47 Ajout des fichiers manquant
  Documentation/Livrables/BD/DicoDesDonnees_G1A-1.pdf
  Documentation/Livrables/BD/dicoDesDonneed.ods
  Documentation/Livrables/GestionProjet/BilanDifficultesReussites/BilanDifficultésRéussitesSem48_G1A-1.pdf
  Documentation/Livrables/GestionProjet/BilanDifficultesReussites/BilanDifficultésRéussitesSem49_G1A-1.pdf
  Documentation/Livrables/GestionProjet/BilanSemaine/CompteRenduGestionProjetSem47_G1A-1.pdf
  Documentation/Livrables/GestionProjet/BilanSemaine/CompteRenduGestionProjetSem48_G1A-1.pdf
  Documentation/Livrables/GestionProjet/BilanSemaine/CompteRenduGestionProjetSem49_G1A-1.pdf
  Documentation/Livrables/GestionProjet/OrdreDuJourReunion/CompteRenduODJ_Réunion_SEM49_G1A-1.pdf
Labels: type: DOCS

#49 schéma relationnel rectifié
  Documentation/Livrables/BD/SchemaRelationel.adoc
Labels: type: BD

#51 Création de la base de données et insertion de donnée
  Documentation/Livrables/BD/generateAvis.py
  Documentation/Livrables/BD/generateCmd.py
  Documentation/Livrables/BD/generatorCB.py
  Documentation/Livrables/BD/generatorClients.py
  Documentation/Livrables/BD/generatorCommande.py
  Documentation/Livrables/BD/scriptCreation.sql
  Documentation/Livrables/BD/scriptInsertionClients.sql
  Documentation/Livrables/BD/scriptisertionproduits.sql
Labels: type: BD

#52 Modification du code + ajout page connexion
  Site_eCommerce/connect.inc.php
  Site_eCommerce/creatCompte.php
  Site_eCommerce/deconnexion.php
  Site_eCommerce/footer.php
  Site_eCommerce/formConnexion.php
  Site_eCommerce/header.php
  Site_eCommerce/images/magasin.png
  Site_eCommerce/index.php
  Site_eCommerce/monCompte.php
  Site_eCommerce/style.css
  Site_eCommerce/styleCompte.css
  Site_eCommerce/styleLogin.css
  Site_eCommerce/traitConnexion.php
  Site_eCommerce/traitCreation.php
Labels: type: WEB

#54 Création de la documentation utilisateur de la page de connexion
  Documentation/Utilisateur/DocUtilisateur.adoc
  Documentation/Utilisateur/SiteWeb/DocTestConnexion.adoc
  Documentation/Utilisateur/SiteWeb/images/code1.PNG
  Documentation/Utilisateur/SiteWeb/images/code2.PNG
  Documentation/Utilisateur/SiteWeb/images/pagebd.PNG
  Documentation/Utilisateur/SiteWeb/images/pagecreacpt.PNG
  Documentation/Utilisateur/SiteWeb/images/pageerreur.PNG
  Documentation/Utilisateur/SiteWeb/images/pagelogin.PNG
  Documentation/Utilisateur/SiteWeb/images/pagelogincrea.PNG
  Documentation/Utilisateur/SiteWeb/images/pageloginval.PNG
  Documentation/Utilisateur/SiteWeb/images/pageloginvalid.PNG
  Documentation/Utilisateur/SiteWeb/images/pagemonCompte.PNG
Labels: type: DOCS
