Repository IUT-Blagnac/sae3-01-devapp-g1a-1, pull requests merged in 2023-01, with the labels that each got.

#57 Ajout de badges (Informations utiles)
  README.adoc
Labels: type: DOCS

#62 Création de la documentation test PYTHON
  Documentation/Tests/Python/DocTestPy.adoc
  Documentation/Tests/Python/images/activity.png
  Documentation/Tests/Python/images/alerteFich.png
  Documentation/Tests/Python/images/co2.png
  Documentation/Tests/Python/images/donneesFich.png
  Documentation/Tests/Python/images/humidity.png
  Documentation/Tests/Python/images/pressure.png
  Documentation/Tests/Python/images/temp.png
  Documentation/Tests/Python/images/tvoc.png
Labels: type: DOCS

#68 Ajout de la documentation utilisateur python
  Applications/Python/DocUtilPython.adoc
  Applications/Python/img/dossier.PNG
  Applications/Python/img/exec.PNG
  Applications/Python/img/pip-install.PNG
Labels: type: DOCS

#69 Ajout de la page produit
  Site_eCommerce/produits.php
  Site_eCommerce/styleProduit.css
Labels: type: WEB

#71 Ajout de la page des détails des produits
  Site_eCommerce/detailProduit.php
  Site_eCommerce/styleDetail.css
Labels: type: WEB

#72 Création de deux procédures stockées
  Documentation/Livrables/BD/addToOrder.sql
  Documentation/Livrables/BD/hasOrdered.sql
Labels: type: BD

#74 Ajout de la documentation test des procédures
  Documentation/Tests/BD/Livrable BD SEM01 G1A-1.docx.pdf
Labels: type: BD

#76 Ajout des documents de gestion de projet
  Documentation/Livrables/GestionProjet/BilanDifficultesReussites/BilanDifficultesReussitesSem01_G1A-1.pdf
  Documentation/Livrables/GestionProjet/BilanDifficultesReussites/BilanDifficultésRéussitesSem50_G1A-1.pdf
  Documentation/Livrables/GestionProjet/BilanSemaine/CompteRenduGestionProjetSem01_G1A-1.pdf
  Documentation/Livrables/GestionProjet/BilanSemaine/CompteRenduGestionProjetSem50_G1A-1.pdf
  Documentation/Livrables/GestionProjet/OrdreDuJourReunion/CompteRenduODJ_Reunion_SEM01_G1A-1.pdf
  Documentation/Livrables/GestionProjet/OrdreDuJourReunion/CompteRenduODJ_Réunion_SEM50_G1A-1.pdf
  Documentation/Tests/Web/Livrable WEB SEM01 G1A-1.docx.pdf
Labels: type: DOCS

#83 Ajout de la page de modification client
  Site_eCommerce/compteClient.php
  Site_eCommerce/styleCompteCli.css
  Site_eCommerce/traitModif.php
Labels: type: WEB

#90 Faire l'interface avec l'utilisateur pour paramétrer un fichier de configuration qui servira au programme python + Visualiser les données graphiquement. (Type de graphique libre)
  Applications/Java/MagicAlfombrAppSrc.zip
Labels: type: JAVA

#91 Ajout des documents de gestion de projet
  Documentation/Livrables/GestionProjet/BilanDifficultesReussites/BilanDifficultésRéussitesSem02_G1A-1.pdf
  Documentation/Livrables/GestionProjet/BilanSemaine/CompteRenduODJ_Reunion_SEM02_G1A-1.pdf.pdf
  Documentation/Livrables/GestionProjet/OrdreDuJourReunion/CompteRenduODJ_Réunion_SEM02_G1A-1.pdf
Labels: type: DOCS

#92 Ajout de la documentation utilisateur du site Web
  Documentation/Utilisateur/SiteWeb/DocUtil.adoc
  Documentation/Utilisateur/SiteWeb/images/AffichagePanier.png
  Documentation/Utilisateur/SiteWeb/images/accueil.png
  Documentation/Utilisateur/SiteWeb/images/cliqueDetail.png
  Documentation/Utilisateur/SiteWeb/images/cliquerCrea.jpg
  Documentation/Utilisateur/SiteWeb/images/connexionPanier.png
  Documentation/Utilisateur/SiteWeb/images/creationCompte.jpg
  Documentation/Utilisateur/SiteWeb/images/decouvrirproduit.png
  Documentation/Utilisateur/SiteWeb/images/detailsProduit.jpg
  Documentation/Utilisateur/SiteWeb/images/detailsProduits.png
  Documentation/Utilisateur/SiteWeb/images/footer.png
  Documentation/Utilisateur/SiteWeb/images/infoCrea.jpg
  Documentation/Utilisateur/SiteWeb/images/login.png
  Documentation/Utilisateur/SiteWeb/images/panier.jpg
  Documentation/Utilisateur/SiteWeb/images/panier.png
  Documentation/Utilisateur/SiteWeb/images/produitsDispo.png
  Documentation/Utilisateur/SiteWeb/images/recherche.jpg
  Documentation/Utilisateur/SiteWeb/images/rechercheProduit.jpg
  Documentation/Utilisateur/SiteWeb/images/rechercheProduit.png
  Documentation/Utilisateur/SiteWeb/images/souvenirMoi.jpg
  Documentation/Utilisateur/SiteWeb/images/validConnexion.jpg
  Documentation/Utilisateur/SiteWeb/images/validLogin.jpg
  Documentation/Utilisateur/SiteWeb/images/valider.jpg
Labels: type: WEB

#93 Ajout de la page panier
  Site_eCommerce/panier.php
  Site_eCommerce/stylePanier.css
Labels: type: WEB

#94 Ajout de la documentation test de la page du panier
  Documentation/Tests/Web/Livrable WEB SEM02 G1A-1.docx.pdf
Labels: type: WEB

#95 Ajout des documents manquants
  Documentation/Tests/BD/Livrable BD SEM02 G1A-1.docx.pdf
  Documentation/Tests/BD/Livrable BD SEM50 G1A-1.docx (3).pdf
  Documentation/Tests/Web/RenduSem50Web_G1A-1.pdf
Labels: type: DOCS

#96 Ajout des liens des nouveaux documents
  README.adoc
Labels: type: DOCS

#99 Modification du gitignore pour accepter les .jar et ajout du jar
  .gitignore
  Applications/Java/MagicAlfombrApp.jar
Labels: type: JAVA

#101 Mise à jour du code source avec les dernière fonctionnalités
  Applications/Java/MagicAlfombrAppSrc.zip
Labels: type: JAVA

#102 85 produire la documentation technique de la solution iot java
  Documentation/Technique/DocTechnique.adoc
  Documentation/Technique/img/accueil.PNG
  Documentation/Technique/img/config.PNG
  Documentation/Technique/img/erreur.PNG
  Documentation/Technique/img/frequence.PNG
  Documentation/Technique/img/packages.png
  Documentation/Technique/img/rep.PNG
  Documentation/Technique/img/valider.PNG
Labels: type: DOCS

#103 Mise à jour des images
  Documentation/Technique/img/accueil.png
  Documentation/Technique/img/config.png
  Documentation/Technique/img/erreur.png
  Documentation/Technique/img/frequence.png
  Documentation/Technique/img/rep.png
  Documentation/Technique/img/valider.png
Labels: type: DOCS

#109 Ajout texte badges dans le README
  README.adoc
Labels: type: DOCS

#110 Fonctionnalité ajouter avis
  Site_eCommerce/detailProduit.php
  Site_eCommerce/traitAvis.php
  Site_eCommerce/traitPanier.php
Labels: type: WEB

#112 Mise à jour de la documentation Python
  Applications/Python/DocUtilPython.adoc
Labels: type: PYTHON

#113 Ajout des documents produits dans le readme
  Documentation/Livrables/GestionProjet/BilanDifficultesReussites/BilanDifficultésRéussitesSem03_G1A-1.pdf
  Documentation/Livrables/GestionProjet/BilanSemaine/CompteRenduGestionProjetSem03_G1A-1.pdf
  Documentation/Livrables/GestionProjet/OrdreDuJourReunion/CompteRenduODJ_Réunion_SEM03_G1A-1.pdf
  README.adoc
Labels: type: DOCS
